---
- name: Install and configure Nginx to serve a static site
  hosts: webservers
  become: yes

  vars_files:
    - vars/main.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - import_tasks: tasks/main.yml
