---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Ensure web root directory exists
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    mode: '0755'

- name: Copy static index.html
  ansible.builtin.copy:
    src: files/index.html
    dest: "{{ web_root }}/index.html"
    mode: '0644'

- name: Deploy Nginx config from template
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx

- name: Ensure Nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
